#
# i18n pour la page register.jsp et la validation.
#
global.register_page=Register Page
global.username=Username
global.password=Password
global.register=Register

global.username_is_required=Username is required
global.username_contains_invalid_characters=Username contains invalid characters
global.username_invalid_length=Username invalid length

global.password_is_required=Password is required
global.password_contains_invalid_characters=Password contains invalid characters
global.password_invalid_length=Password invalid length